#!/bin/sh
# SPDX-License-Identifier: BSD-3-Clause
# (c) 2021-2022, Konstantin Demin

set -e

[ -z "${VERBOSE}" ] || set -xv

## remove aptitude (with many thanks)
Q=1 /opt/apt.sh purge aptitude

rm -rf \
  /var/lib/aptitude \
  "${HOME:-$PWD}/.aptitude"
