#!/bin/sh
# SPDX-License-Identifier: BSD-3-Clause
# (c) 2021-2022, Konstantin Demin

set -e

: "${XROOT:=/x}"

[ -z "${VERBOSE}" ] || set -xv

rm -rf \
  /var/lib/apt/lists/auxfiles \

truncate -s 0 \
  /var/lib/dpkg/available \

unset XGLOB_PIPE XGLOB_DIRS

"${XROOT}/glob" /var/lib/apt <<-EOF
	delete=listchanges*
	delete=lists/**
	keep=lists/lock
EOF

"${XROOT}/glob" /var/lib/dpkg <<-EOF
	delete=*-old
EOF

"${XROOT}/glob" /var/cache/apt <<-EOF
	delete=**
	keep=archives/lock
EOF

"${XROOT}/glob" /var/log <<-EOF
	delete=alternatives.log
	delete=alternatives.log.*
	delete=apt/*.log
	delete=apt/*.log.*
	delete=aptitude
	delete=aptitude.*
	delete=dpkg.log
	delete=dpkg.log.*
EOF
