#!/bin/sh
# SPDX-License-Identifier: BSD-3-Clause
# (c) 2021-2022, Konstantin Demin

set -ef

: "${XROOT:=/x}"

[ -z "${VERBOSE}" ] || set -xv

unset XGLOB_PIPE
XGLOB_DIRS=1 \
"${XROOT}/glob" /etc - "${XROOT}/conf/cleanup/etc" <<-EOF
	delete=.pwd.lock
	delete=group-
	delete=gshadow-
	delete=passwd-
	delete=shadow-
	delete=subgid-
	delete=subuid-
EOF
