#!/bin/sh
# SPDX-License-Identifier: BSD-3-Clause
# (c) 2021-2022, Konstantin Demin

set -ef

: "${XROOT:=/x}"

[ -z "${VERBOSE}" ] || set -xv

unset XGLOB_PIPE
XGLOB_DIRS=1 \
"${XROOT}/glob" / - "${XROOT}/conf/cleanup/python-cache" <<-EOF
	delete=**/*.pyc
	delete=**/*.pyo
	delete=**/__pycache__
EOF
