#!/bin/sh
# SPDX-License-Identifier: BSD-3-Clause
# (c) 2022, Konstantin Demin

set_output() {
	if echo "$1" | grep -Eq '/$' ; then
		mktemp -p "$1"
	else
		echo "$1"
	fi
}

if [ -n "${ELF_SODEPS_OUT}" ] ; then
	out=$(set_output "${ELF_SODEPS_OUT}")
	: "${out:?}"
	exec 1> "${out}"
fi

for i ; do
	ldd "$i" 2>/dev/null \
	| sed -En '
	/^.+ => (.+) \(\S+\)$/     {s##1|'"$i"'|\1#p}
	/^\s*(\S.+) => not found$/ {s##0|'"$i"'|\1#p}
	'
done
