#!/bin/sh
# SPDX-License-Identifier: BSD-3-Clause
# (c) 2021-2022, Konstantin Demin

set -ef

export DEBCONF_NONINTERACTIVE_SEEN=true
export DEBIAN_FRONTEND=noninteractive
export DEBIAN_PRIORITY=critical
export TERM=linux

act=update
for i ; do
	case "$i" in
	-*) ;;
	*) act="$i" ; break ;;
	esac
done

## WIP:
## try guess whether better to use apt instead of aptitude
## or vice versa
flavour=apt
if [ -z "${WITH}" ] ; then
	case "${act}" in
	install|purge|reinstall|remove|search)
			## traverse arguments
			for i ; do
				case "$i" in
				## aptitude's flags
				-r|-R) flavour=aptitude ; break ;;
				## skip other flags
				-*) ;;
				## aptitude's selectors and modifiers
				*[?~\&]*) flavour=aptitude ; break ;;
				*+M)      flavour=aptitude ; break ;;
				*[-_=:])  flavour=aptitude ; break ;;
				esac
			done
	;;
	esac
fi
## honour provided flavour value
flavour="${WITH:-$flavour}"
## except for these
case "${act}" in
## apt only
autoremove|download|satisfy|update|upgrade)
	flavour=apt
;;
## aptitude only
autoclean|build-dep|build-depends|forbid-version|forget-new|hold|keep-all|markauto|safe-upgrade|unhold|unmarkauto)
	flavour=aptitude
;;
## builtin actions
install-aptitude)
	flavour=aptitude
;;
install-*|list-*)
	flavour=apt
;;
esac
## sanity check
case "${flavour}" in
apt|aptitude) ;;
*)
	env printf "%q: unknown backend: %q\\n" "$0" "${flavour}" 1>&2
	exit 1
;;
esac

## make script quiet as possible/desired
_q() { /x/quiet "$@" ; }
_cq=
case "$Q" in
0) ;;
1) _cq=_q ;;
esac

find_fresh_ts() {
	{
		find "$@" -exec stat -c '%Y' '{}' '+' 2>/dev/null || :
		## duck and cover
		echo 1
	} | sort -rn | head -n 1
}

xapt_update() {
	## update package lists; may fail sometimes,
	## e.g. soon-to-release channels like Debian "bullseye" @ 22.04.2021
	if [ $# = 0 ] ; then
		## (wannabe) smart package list update
		ts_sources=$(find_fresh_ts /etc/apt -name '*.list' -type f)
		ts_lists=$(find_fresh_ts /var/lib/apt/lists/ -maxdepth 1 -name '*_Packages' -type f)
		if [ ${ts_sources} -gt ${ts_lists} ] ; then
			_q apt -qq -y update
		fi
	else
		${_cq} apt "$@"
	fi
}

xapt_dpkg_avail_hack() {
	release=$( ( . /etc/os-release ; echo "${VERSION_CODENAME}" ; ) )
	dpkg_avail='/var/lib/dpkg/available'
	## if ${release} is empty then we're on Debian sid or so :)
	case "${release}" in
	stretch|buster|bionic|focal)
		## ref: https://unix.stackexchange.com/a/271387/49297
		if [ -s "${dpkg_avail}" ] ; then
			return
		fi
		_q /usr/lib/dpkg/methods/apt/update /var/lib/dpkg apt apt
	;;
	*)
		touch "${dpkg_avail}"
	;;
	esac
}

xapt_list_installed() {
	dpkg-query -W \
		-f='${Package}:${Architecture}|${db:Status-Abbrev}\n' \
	| sed -En '/^(.+)\|[hi]i $/{s//\1/;p}' \
	| sort -V
}

xapt_list_martians() {
	t=$(mktemp) ; : "${t:?}"

	dpkg-query -W \
	    -f='${Package}:${Architecture} ${Version} status="${db:Status-Abbrev}"\n' \
	| grep -Ev '"ii "$' \
	| sort -V \
	> "$t"

	if [ -s "$t" ] ; then
		if [ -t 1 ] ; then
			echo '# "martian" packages (unusual state):' 1>&2
		fi
		cat "$t"
	fi

	rm -f "$t"
}

xapt_list_auto__int() {
	mawk '
	/^Package:/,/^$/ {
	    if ($1 == "Package:")        { pkg = $2; }
	    if ($1 == "Architecture:")   { arch = $2; }
	    if ($1 == "Auto-Installed:") { is_auto = $2; }
	    if ($0 == "") {
	        if (is_auto == 1) { print pkg ":" arch; }
	    }
	}
	' /var/lib/apt/extended_states \
	| sort -V \
	> "$w/auto.pkg"

	while : ; do
		[ -s "$w/auto.pkg" ] || break

		## fix:
		## /var/lib/apt/extended_states stores (some) arch:all entries as arch:native
		sed -En '/^([^:]+):all$/ {s##/^\1:.+$/ {s//\1:all/}#p}' \
		< "$w/all" \
		> "$w/auto.sed"
		
		if [ -s "$w/auto.sed" ] ; then
			sed -E -f "$w/auto.sed"
		else
			cat
		fi < "$w/auto.pkg"

		break
	done
}

xapt_list_auto() {
	w=$(mktemp -d) ; : "${w:?}"

	xapt_list_installed > "$w/all"
	xapt_list_auto__int

	rm -rf "$w"
}

xapt_list_manual__int() {
	xapt_list_auto__int > "$w/auto"
	if [ -s "$w/auto" ] ; then
		grep -Fxv -f "$w/auto"
	else
		cat
	fi < "$w/all"
}

xapt_list_manual() {
	w=$(mktemp -d) ; : "${w:?}"

	xapt_list_installed > "$w/all"
	xapt_list_manual__int

	rm -rf "$w"
}

apt_install_aptitude() {
	if command -v aptitude >/dev/null ; then
		return 0
	fi

	_q apt -qq -y install aptitude
}

case "${act}" in
install|upgrade|safe-upgrade|full-upgrade)
	xapt_update
;;
esac

if [ "${flavour}" = aptitude ] ; then
	xapt_update
	xapt_dpkg_avail_hack
	apt_install_aptitude
fi

case "${act}" in
list-installed)
	xapt_list_installed
;;
list-martians)
	xapt_list_martians
;;
list-auto)
	xapt_list_auto
;;
list-manual)
	xapt_list_manual
;;
install-aptitude)
;;
list-*|install-*)
	env printf "unknown action: %q" "${act}" 1>&2
	exit 1
;;
update)
	xapt_update "$@"
;;
*)
	case "${flavour}" in
	apt)
		${_cq} apt -qq -y "$@"
	;;
	aptitude)
		${_cq} aptitude -y "$@"
	;;
	esac
;;
esac
