#!/bin/sh
# SPDX-License-Identifier: BSD-3-Clause
# (c) 2022, Konstantin Demin

set -ef

: "${XROOT:=/x}"

## internal methods
case "$1" in
--begin)
	## begin "build session"
	shift

	w=$(mktemp -d) ; : "${w:?}"

	"${XROOT}/apt" list-installed > "$w/installed.0"
	"${XROOT}/apt" list-manual    > "$w/manual.0"

	if [ -z "$*" ] ; then
		echo 'nothing was selected as build-deps' 1>&2
	else
		if ! ( "${XROOT}/apt" ${BUILDWRAP_METHOD:-install} "$@" ; ) </dev/null 1>&2 ; then
			rm -rf "$w"
			exit 1
		fi

		"${XROOT}/apt" list-installed > "$w/installed.1"
		"${XROOT}/apt" list-manual    > "$w/manual.1"
	fi

	echo "$w"
	exit 0
;;
--end)
	## end "build session"
	shift

	w="$1"

	ok=
	while : ; do
		[ -d "$w" ]             || break
		[ -s "$w/installed.0" ] || break
		[ -s "$w/manual.0" ]    || break
		ok=1 ; break
	done
	if [ -z "${ok}" ] ; then
		echo 'wrong state!' 1>&2
		exit 1
	fi

	x="$w/keep"
	if [ -s "$x" ] ; then
		set +e
		grep -Fxv -f "$w/installed.0" "$x" > "$x.manual"
		set -e
		xargs -r "${XROOT}/quiet" apt-mark manual < "$x.manual"
	fi

	"${XROOT}/apt" list-installed > "$w/installed.2"
	"${XROOT}/apt" list-manual    > "$w/manual.2"

	set +e

	x="$w/installed.1"
	if ! [ -s "$x" ] ; then x="$w/installed.2" ; fi
	grep -Fxv -f "$w/installed.0" \
	"$x" \
	> "$w/installed.diff"

	x="$w/manual.1"
	if ! [ -s "$x" ] ; then x="$w/manual.0" ; fi
	grep -Fxv -f "$x" \
	"$w/manual.2" \
	> "$w/manual.diff"

	if [ -s "$w/manual.diff" ] ; then
		grep -Fxv -f "$w/manual.diff" \
		"$w/installed.diff"
	else
		cat "$w/installed.diff"
	fi \
	> "$w/pkg.remove"

	xargs -r "${XROOT}/apt" purge < "$w/pkg.remove" 1>&2

	rm -rf "$w"
	exit 0
;;
esac

w=$("$0" --begin ${BUILDWRAP_DEPS})

export BUILDWRAP_KEEP="$w/keep"
: > "${BUILDWRAP_KEEP}"

set +e
"$@"
r=$?

"$0" --end "$w"

exit $r
